version: '2'
services:
  gcb-alpine-curl:
    build: .
    container_name: gcb-alpine-curl
    image: gcb_alpine_curl
    restart: always

  gcb-apache2:
    image: httpd
    container_name: gcb-apache2
    restart: always
    volumes:
      - ./test_1MB.jpg:/usr/local/apache2/htdocs/test_1MB.jpg

