name: Examples Directory Tests Run
run-name: Examples Directory Test Run - ${{ github.ref_name }}

on:
  schedule:
    - cron: '0 0 * * *'
      branches: [ "main" ]

  #push: 
  #  branches: [ "workflow-tweaks" ]

  workflow_dispatch:

jobs:
  #TODO: is there a way to do this that's even more light-weight?
  check-commits:
    #runs-on: self-hosted #literally just for the energy savings: so GitHub doesn't have to boot up a VM
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      recent_examples_commit: ${{ steps.check_date_examples_repo.outputs.recent_examples_commit }}
      recent_gmt_commit: ${{ steps.check_date_gmt_dev.outputs.recent_gmt_commit }}
    steps:
      - name: check if latest commit is less than a day ago
        id: check_date_examples_repo
        continue-on-error: true
        if: ${{ github.event_name == 'schedule' }}
        run: |
          dateofcommit=$(curl -s https://api.github.com/repos/green-coding-berlin/example-applications/commits/main | jq -r '.commit.author.date')
          commit_timestamp=$(date --date "$dateofcommit" +'%s')
          one_day_ago=$(date --date '1 day ago' +'%s')
          [ $commit_timestamp -gt $one_day_ago ] && echo "recent_examples_commit=true" >> $GITHUB_OUTPUT

      - name: check if latest gmt commit is less than a day ago
        id: check_date_gmt_dev
        continue-on-error: true
        if: ${{ github.event_name == 'schedule' }}
        run: |
          dateofcommit=$(curl -s https://api.github.com/repos/green-coding-berlin/green-metrics-tool/commits/dev | jq -r '.commit.author.date')
          commit_timestamp=$(date --date "$dateofcommit" +'%s')
          one_day_ago=$(date --date '1 day ago' +'%s')
          [ $commit_timestamp -gt $one_day_ago ] && echo "recent_gmt_commit=true" >> $GITHUB_OUTPUT

  run-tests:
    needs: check-commits
    if: ${{ needs.check-commits.outputs.recent_examples_commit == 'true' ||  needs.check-commits.outputs.recent_gmt_commit == 'true' || github.event_name == 'workflow_dispatch'}}
    #runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Examples Directory
        uses: actions/checkout@v3
        with:
          path: examples-directory

      - name: Checkout Green Metrics Tool
        uses: actions/checkout@v3
        with:
          repository: green-coding-berlin/green-metrics-tool
          submodules: 'true'
          path: green-metrics-tool

      - name: Install python testing dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install fastapi pytest psycopg2 numpy pandas xgboost statsmodels scipy scikit-learn
      
      - name: Run Prereqs and Install Script
        working-directory: ./green-metrics-tool
        run: |
          sudo apt install lm-sensors libsensors-dev libglib2.0-0 libglib2.0-dev
          ./install.sh -p testpw
      - name: Turn off metric providers
        working-directory: ./green-metrics-tool
        run: |
          ./disable-metric-providers.sh System Sensors Debug
          
      - name: Setup Test environment
        working-directory: ./green-metrics-tool/test
        run: |
          python3 setup-test-env.py
          
      - name: Start Test container
        working-directory: ./green-metrics-tool/test
        run: |
         ./start-test-containers.sh -d
     
      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
          
      - name: Run Tests
        working-directory: ./examples-directory/test
        run: |
          pytest
          
      - name: Stop Containers
        if: always()
        working-directory: ./green-metrics-tool/test
        run: |
          ./stop-test-containers.sh